# Default values for a papyrus deployment.

# Values that configure running a papyrus deployment on Kubernetes.
# An HTTP RPC endpoint of the Ethereum entry-point (A local Ethereum client, Infura, etc.).
ethereumApiUrl: ETHEREUM_API_URL
rustLogLevel: "info"

# The Docker image (including any tag and repository name)
image:
  repository: ghcr.io/starkware-libs/papyrus
  tag: latest
  pullPolicy: Always

# The default resources for the pod.
# resources:
#   limits:
#     cpu: 100m
#     memory: 500Mi
#   requests:
#     cpu: 100m
#     memory: 500Mi

# Service variables for a papyrus pod.
services:
  # RPC API.
  rpc:
    type: ClusterIP
    port: 8080
    protocol: TCP
  # Monitoring API.
  monitoring:
    type: ClusterIP
    port: 8081
    protocol: TCP

# Persistent volume claim variables for a papyrus pod.
pvc:
  size: 1000Gi
  storageClass: premium-rwo
  restoreFromSnapshot:
    enabled: true
    volumeSnapshotClassName: papyrus
    snapshotName: papyrus-benchmark

# Configure Ingress.
ingress:
  # Ingress class type.
  type: gce
  # Ingress object name in Kubernetes.
  name: ssl-proxy
  # Host name to create Ingress rules.
  host:
  # Ingress path type.
  pathType: ImplementationSpecific
  # Annotations to apply to the node ingress.
  annotations: |
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
