[package]
name = "papyrus_load_test"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
anyhow.workspace = true
goose.workspace = true
once_cell.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
test_utils = { path = "../test_utils" }
tokio.workspace = true
rand.workspace = true
reqwest.workspace = true