chain_id: SN_MAIN
central:
    concurrent_requests: 10
    url: https://alpha-mainnet.starknet.io/
    retry:
        retry_base_millis: 30
        retry_max_delay_millis: 30000
        max_retries: 10
#   Optional headers for SN-client.
#   http_headers:
#       header_name: header_value

gateway:
    server_address: 0.0.0.0:8080
    max_events_chunk_size: 1000
    max_events_keys: 100

monitoring_gateway:
    server_address: 0.0.0.0:8081

storage:
    db:
        path: ./data
        max_size: 1099511627776 # 1TB.

sync:
    block_propagation_sleep_duration_secs: 10
    recoverable_error_sleep_duration_secs: 10