refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l} {t} - {m}{n}"
  aggregated_log_file:
    kind: file
    path: "logs/log.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {l} {t}- {m}{n}"

root:
  level: debug
  appenders:
    - stdout
    - aggregated_log_file
